### PR TITLE
Added controller for login and callback endpoints

### PR DESCRIPTION
**Pull request by sbryzak**
This PR adds the empty controller for the login and callback endpoints.  Implementation will come in a later PR, this PR only covers the controller definition and the wiring.

Fixes https://issues.redhat.com/browse/CRT-1634

### CODE REVIEW

**Review by xcoulon — COMMENTED** [review]
do we need to commit in the repository all the code that is generated by Goa?

**Comment by sbryzak** [comment]
@xcoulon it's required to compile, so unless the build environment has goagen installed it's needed.

**Comment by sbryzak** [comment]
Further to my previous comment, I could probably update the Dockerfile to install goagen, however it would still impose an additional burden for any developer that just wants to check out the code and build it in their IDE.

**Comment by xcoulon** [comment]
> @xcoulon it's required to compile, so unless the build environment has goagen installed it's needed.

That's exactly my point: we could use `make` to install and run `goagen`, so that all those files can stay local (we could generate the files when running `make test` and `make build` for example). 

Also, I assume we'll need the tool to regenerate the code when the design changes, won't we?

**Comment by xcoulon** [comment]
> Further to my previous comment, I could probably update the Dockerfile to install goagen, however it would still impose an additional burden for any developer that just wants to check out the code and build it in their IDE.

I don't think we need a Docker image for that. We could include `goagen` in a `tools.go` file such as we do [on our api repository](https://github.com/codeready-toolchain/api/blob/master/tools.go) and use a `make` goal. WDYT?

**Comment by xcoulon** [comment]
> > Further to my previous comment, I could probably update the Dockerfile to install goagen, however it would still impose an additional burden for any developer that just wants to check out the code and build it in their IDE.
> 
> I don't think we need a Docker image for that. We could include `goagen` in a `tools.go` file such as we do [on our api repository](https://github.com/codeready-toolchain/api/blob/master/tools.go) and use a `make` goal. WDYT?

Actually, this is an orthogonal concern: the way we install and use the tooling is not related to committing or not the generated code in the repository.

**Review by alexeykazakov — CHANGES_REQUESTED** [review]
I agree with Xavier.
Let's do the following before we resume introducing any new code to the repo:
- add proper makefile targets for all main actions such as: build, test, clean, etc
- include code generation into `make build` so we don't have to manually re-generate the code and commit it to git

**Review by alexeykazakov — COMMENTED** [review]
```
$ make build
mkdir -p /home/igels/go/src/github.com/codeready-toolchain/sandbox-auth/gen
podman build --volume /home/igels/go/src/github.com/codeready-toolchain/sandbox-auth/gen:/gen:z,U -t sandbox-auth .
STEP 1/9: FROM golang:1.18
Error: error creating build container: short-name "golang:1.18" did not resolve to an alias and no unqualified-search registries are defined in "/etc/containers/registries.conf"
make: *** [Makefile:7: build] Error 125
```

**Review by alexeykazakov — APPROVED** [review]
`make test` still doesn't work for me but let's address it in a separate PR

**Pull request merged**
